### ISSUE TITLE
NODWELL support?

### ISSUE THREAD

**Issue by larsw** [phulst/node-tile38#31]
Hi,

 Is it possible to shoe horn in the `NODWELL` keyword when setting up roaming geofences?

 https://tile38.com/topics/roaming-geofences/

**Comment by phulst** [comment]
should be pretty easy to add, I'll take a stab at it this week

**Comment by phulst** [comment]
thanks for the PR. I've decided to close this one but have implemented it in a slightly different way. You can now use nodwell roam as follows: 

```
client.nearbyQuery('people').nodwell().roam('friends', '*', 100);
```

Your approach would have worked fine as well, but I think this is a bit more consistent with how I've implemented other optional keywords. 
I had addressed the test failures already as well. 
Working on a new revision and catching up with all the new commands and options that have been added since I last released a version.
