### ISSUE TITLE
Need an example for websockets in Nodejs

### ISSUE THREAD

**Issue by O-verlord** [phulst/node-tile38#49]

**Comment by phulst** [comment]
This is not the right place to ask for generic Node.js/websocket implementation info. 
As it relates to the node-tile38 library: this library does use a websocket implementation to connect to Tile38 for live geofences, but when working with node-tile38 you don't need to use the Websocket API directly. 

For an example of how to use live geofences, see this code: 
https://github.com/phulst/node-tile38/blob/master/examples/search.js

If you have specific issues with node-tile38, please give me a detailed description of what you're trying to accomplish and where you are stuck. Otherwise, there's not much I can do to help.

**Comment by phulst** [comment]
Kept open for almost 5 months, but no response. Closing this now.
